### ISSUE TITLE
get formated Phone

### ISSUE THREAD

**Issue by eafelix** [razagill/react-phone-input#19]
Hi guys how are you? It's very cool the component, but I think maybe it will better return the value with spaces so that we can get the country code and the primary phone number separately. Or already do we have? Of course it will be a PR.
Thks

**Comment by sample-usr** [comment]
@eafelix Can you tell me more about your use case? Instead of returning the number with spaces it might be worthwhile to have a method to access the current country code.

**Comment by eafelix** [comment]
I need to use it with Authy https://www.authy.com/ to do a dual factor auth.
The problem is the API need the country code separately, and when I saw other services like this, all need to be provided apart.

**Comment by sample-usr** [comment]
@eafelix Sorry for the delay, I won't have much till the end of the month. If you want, you can send me a PR for this issue (it should be rather easy, just adding a new method for returning the country code state), otherwise I'll hopefully get it finished by in the next couple of weeks.
