### ISSUE TITLE
peerDependencies on react@^0.13.2

### ISSUE THREAD

**Issue by dsteinbach** [razagill/react-phone-input#2]
Can this be bumped to the latest react or will this break this npm?

**Comment by sample-usr** [comment]
@dsteinbach I haven't tested it yet with the latest react. I'll try it out as soon as I get some time and will bump it if everything looks fine.

**Comment by dsteinbach** [comment]
Or it would be better if it could depend on a range of react versions

**Comment by sample-usr** [comment]
Fix: 7ec145552cac522e8134088b78c13374d4923edf
