### ISSUE TITLE
Can't over right the less file

### ISSUE THREAD

**Issue by ShanthiSenguttuvan** [razagill/react-phone-input#21]
Any changes made in react-phone-input-style.less does not affect the component.  It will be better if you provide a option to over right the react-phone-input-style.less file.

**Comment by sample-usr** [comment]
@ShanthiSenguttuvan That less file only get recompiled when we build the project from the source again. What you want is to add another less/css file in your project and overwrite the `.react-tel-input` with whatever styling you want. You can use the `react-phone-input-style.less` as a guide as to which properties you would like to overwrite.

**Comment by ShanthiSenguttuvan** [comment]
got it. Thank you so much.
