### ISSUE TITLE
Unknow props warning when using with React 15

### ISSUE THREAD

**Issue by raapperez** [razagill/react-phone-input#22]
I'm receiving the following warning from React 15:
`Warning: Unknown props defaultCountry, onlyCountries, excludeCountries on <input> tag. Remove these props from the element.`

**Comment by iduuck** [comment]
Also getting the following error:

```
Warning: Unknown props `preferredCountries`, `autoFormat`, `onlyCountries`, `excludeCountries`, `defaultCountry`, `isValid`, `flagsImagePath`, `onEnterKeyPress` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

---

Will do a pull request, when I have time :shipit:

**Comment by iduuck** [comment]
@raapperez Made a pull request. If the author isn't working on this project anymore, please refer to the forked repository: https://github.com/kreativgebiet/react-phone-input

**Comment by sample-usr** [comment]
@raapperez @iDuuck Still working on this, albeit a bit slow but hopefully that'll change soon :)
