### ISSUE TITLE
onChange firing on componentDidMount

### ISSUE THREAD

**Issue by dsteinbach** [razagill/react-phone-input#4]
Was just wondering if there are necessary use cases for keeping the onChange in componentDidMount because when using this phone component with validation libraries like formsy or redux-form this automatically sets the input to be in a non-pristine state, meaning on pageload the value of this field is already invalid and displaying our validation error message.  Permission to remove?

**Comment by dsteinbach** [comment]
You can think of it like your phone component is basically a number formatter. Numbers in, formatted numbers out. It shouldnt have output unless there is input.

**Comment by sample-usr** [comment]
@dsteinbach sorry for the delay, was a bit buys. Yeah, that was added because of a local use case we had but I just checked and that's no longer required, also thanks for the pull. I'll merge it now.
