### ISSUE TITLE
Access to onFocus, onBlur and other kind of events

### ISSUE THREAD

**Issue by RaitoBezarius** [razagill/react-phone-input#7]
Currently, react-phone-input does not expose onFocus / onBlur and other kind of events.

This is important when you have to trigger events based on focus / blur events.

My suggestion would be:
- In the already used events: onChange, onFocus for example, you could check for `this.props.onChange` or `this.props.onFocus` and call back them.
- Add a destructuration of all props on the input component at the top so that you can overwrite properly the other props.

**Comment by sample-usr** [comment]
Hey @RaitoBezarius thanks for pointing it out. I'm currently short of time but would appreciate a PR if you would be willing to submit one, otherwise I can get to it later.

**Comment by RaitoBezarius** [comment]
@razagill Sure thing!
